Ruby/BlogProject-master/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :comments, only: [:edit, :create, :update, :destroy]
  resources :blog_posts
  root 'blog_posts#index'
  # get 'user_posts' => 'blog_posts#user_posts'
  get '/:name' => 'blog_posts#user_posts', as: :user_posts

end

Ruby/BlogProject-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ruby/BlogProject-master/app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, :blog_entry, presence: true
  validates :title, uniqueness: true, length: {maximum: 140}

  paginates_per 3
end

Ruby/BlogProject-master/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post
  belongs_to :user
  validates :comment_entry, :blog_post_id, presence: true
end

Ruby/BlogProject-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, uniqueness: true
end

Ruby/BlogProject-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

Ruby/BlogProject-master/app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  include ApplicationHelper

  def index
    @blog_posts = BlogPost.all.page(params[:page])
  end

  def show
    @comment = Comment.new
  end

  def user_posts
    @user = User.find_by(username: params[:name])
  end

  def edit
    no_access_visitors(current_user, @blog_post)
  end

  def new
    @blog_post = BlogPost.new #Creating a new instance of BlogPost (remember initialize from ruby classes)
  end

  def create
    @blog_post = BlogPost.new(blog_post_params) #method we will set up in a second here. This method will help us allow all of the BlogPost attributes
    respond_to do |format|
      if @blog_post.save #Method from the blogPost class
        	format.html { redirect_to blog_post_url(@blog_post), notice: "Blog Post
    		was created successfully."} #route when BlogPost successfully saved to database
      else
        format.html {render :new} #render to new blog post page when blog post can't be saved to database
      end
    end
  end

  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params) #blog_post.update is from the BlogPost class
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was updated successfully"}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @blog_post.destroy #Method from the BlogPost class
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Your Blog Post was DESTROYEDDDDDDDDDD!!!!!!!!!"}
      # Route to when a blog post is destroyed. I could have set instead also root_url as BlogPost index view is also the root page
    end
  end

  private

    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    end
    def blog_post_params
      params.require(:blog_post).permit(:title, :blog_entry, :user_id)
    end

end

Ruby/BlogProject-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment was successfully created!"}
      else
        format.html { redirect_to :back, notice: "Comment failed to post!"}
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment was updated successfully!"}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @comment.destory
    respond_to do |format|
      format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Your comment was destroyed!"}
    end
  end


  def edit
  end

  private


    def comment_params
      params.require(:comment).permit(:user_id, :comment_entry, :blog_post_id)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end
end

Ruby/BlogProject-master/app/helpers/application_helper.rb
module ApplicationHelper

  def no_access_visitors(current_user, post_user)
    unless current_user.id == post_user.user_id
      redirect_to root_url
    end
  end
end

Ruby/BlogProject-master/app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

Ruby/BlogProject-master/app/helpers/comments_helper.rb
module CommentsHelper
end

Ruby/BlogProject-master/app/views/blog_post/user_post.html.erb
<h1>All Posts by
  <b><%= @user.username %></%>
</b>
</h1>

<% @user.blog_posts.each do |blog_post| %>
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <h3><%= link_to blog_post.title, blog_post %></h3>
      <p>
        <em>posted on
          <%= blog_post.created_at.strftime("%m/%d/%Y at %l:%M%P") %></em>
      </p>
      <p>
        <%= blog_post.blog_entry.html_safe %>
      </p>
      <p>
        <% if current_user.id == blog_post.user_id %>
        <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
        <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
    </p>
  </div>
</div>
</div>
<% end %>

Ruby/BlogProject-master/app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>
<% if @blog_post.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@blog_post.errors.count, "error") %>
      prohibited this blog_post from being saved:
    </h2>
    <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
  <%= form.text_field :title, placeholder: "Blog Entry Title", class: "form-control" %>
</div>

<div class="form-group">
  <%= form.hidden_field :user_id, value: current_user.id %>
</div>

<div class="form-group">
  <%= form.text_area :blog_entry, placeholder: "Tell Us Something...", rows: 12, class: "form-control" %>
</div>

<div class="actions">
  <%= form.submit "Submit", class: "btn btn-primary" %>
</div>
<% end %>

Ruby/BlogProject-master/app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", blog_post_path(@blog_post), class: "btn btn-info" %>

<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default"%>

Ruby/BlogProject-master/app/views/blog_posts/index.html.erb
<% if current_user!= nil %>
<h1>Welcome <%= current_user.username %></h1>
<% end %>
<h2>Current Blog Posts</h2>

<div class="row">
  <% @blog_posts.each do |blog_post| %>
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= blog_post.title %>
        </div>
        <div class="panel-body">
          by <em><%= link_to blog_post.user.username, user_posts_path(name: blog_post.user.username) %></em><br>
          <p><i>Created: <%= time_ago_in_words(blog_post.created_at) %> ago</i></p>
          <p><%= blog_post.blog_entry %></p>
        </div>
        <div class="panel-footer">
          <%= link_to "Show", blog_post, class:"btn btn-info" %>
          <% if current_user!= nil && current_user.id == blog_post.user_id %>
          <%= link_to "Edit", edit_blog_post_path(blog_post), class: "btn btn-warning" %>
          <%= link_to "Destroy", blog_post_path(blog_post), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New Blog Post", new_blog_post_path, class: "btn btn-success" %>
<%= paginate @blog_posts %>

Ruby/BlogProject-master/app/views/blog_posts/new.html.erb
<h1>Create a New Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>

Ruby/BlogProject-master/app/views/blog_posts/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @blog_post.title %>
  </div>
  <div class="panel-body">
    <p><%= @blog_post.user.username %></p>
    <p><%= time_ago_in_words(@blog_post.created_at) %> ago</p>
    <p><%= @blog_post.blog_entry %></p>
  </div>
  <div class="panel-footer">
    <% if user_signed_in? && current_user.id == @blog_post.user_id %>
    <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn- warning" %>
    <% end %>
    <%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>
  </div>
  <div class="panel panel-success">
    <div class="panel-heading">
      Make a Comment....
    </div>
    <div class="panel-body">
      <% if user_signed_in? %>
      <%= render 'comments/form' %>
      <% else %>
      <p> <%= link_to "Sign In to Comment", new_user_session_path %> </p>
      <% end %>
    </div>
  </div>
  <div class="panel panel-success">
    <div class="panel-heading">
      All Comments...
    </div>
    <div class="panel-body">
      <%= render @comment %>
    </div>
  </div>
</div>

Ruby/BlogProject-master/app/views/blog_posts/user_posts.html.erb
<h1>All Posts by
  <b><%= @user.username %></%>
</b>
</h1>

<% @user.blog_posts.each do |blog_post| %>
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <h3><%= link_to blog_post.title, blog_post %></h3>
      <p>
        <em>posted on
          <%= blog_post.created_at.strftime("%m/%d/%Y at %l:%M%P") %></em>
      </p>
      <p>
        <%= blog_post.blog_entry.html_safe %>
      </p>
      <p>
        <% if current_user.id == blog_post.user_id %>
        <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
        <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
    </p>
  </div>
</div>
</div>
<% end %>

Ruby/BlogProject-master/app/views/comments/_comment.html.erb
<% @blog_post.comments.each do |comment| %>
<h4>
<h4><%= link_to comment.user.username, user_posts_path(name: comment.user.username) %></h4>
  <p><%= time_ago_in_words(comment.created_at) %>
    ago</p>
  <p><%= comment.comment_entry %></p>
<% end %>

Ruby/BlogProject-master/app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>
<% if @comment.errors.any? %>
  <div class='error_explanation'>
    <h2><%= pluralize(@comment.errors.count, "error") %>
      prohibited this blog post from being saved:
    </h2>
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group hidden">
  <%= form.number_field :user_id, value: current_user.id %>
</div>
<div class="form-group">
  <%= form.text_area :comment_entry, rows: 4, class: "form-control", placeholder: "Enter comment here...." %>
</div>
<div class="form-group hidden">
  <%= form.number_field :blog_post_id, value: @blog_post.id %>
</div>
<div class="actions">
  <%= form.submit "Set Comment", class: "btn btn-default" %>
</div>
<% end %>

Ruby/BlogProject-master/app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

Ruby/BlogProject-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "All Blog Posts", root_path, class: "navbar-brand" %></li>
            <% if user_signed_in? %>
              <li><%= link_to "New Blog Post", new_blog_post_path %></li>
            <% end %>
          </ul>

          <!-- <a class="navbar-brand" href="#">Brand</a> -->
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_tag current_user.email, size: 20 %><%= current_user.username %>
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
        <!-- <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a> <ul class="dropdown-menu"> <li><a href="#">Action</a></li> <li><a
        href="#">Another action</a></li> <li><a href="#">Something else here</a></li> <li role="separator" class="divider"></li> <li><a href="#">Separated link</a></li> <li role="separator" class="divider"></li> <li><a href="#">One more separated
        link</a></li> </ul> </li> </ul> <form class="navbar-form navbar-left"> <div class="form-group"> <input type="text" class="form-control" placeholder="Search"> </div> <button type="submit" class="btn btn-default">Submit</button> </form> <ul class="nav
        navbar-nav navbar-right"> <li><a href="#">Link</a></li> <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a> <ul
        class="dropdown-menu"> <li><a href="#">Action</a></li> <li><a href="#">Another action</a></li> <li><a href="#">Something else here</a></li> <li role="separator" class="divider"></li> <li><a href="#">Separated link</a></li> </ul> </li> </ul> -->
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->

  </nav>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>